# Welcome to Jekyll!
#

# Site settings
title: Another Worlds traveling
description: |
  My name is Vladi and I've traveled the world.  
  I'm here to inspire you.
owner: Vladimir Grankovsky # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: anotherworlds@vladimirgrankovsky.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anotherworlds.net" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/hidobo
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
